services:
  devcontainer:
    networks:
      - internal
    build:
      context: ../../
      dockerfile: .devcontainer/cuda/Dockerfile
    volumes:
      - ./:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  internal:
    driver: bridge

volumes:
  config:
